### PR TITLE
Better console debug messages while loading custom biomes.

### PR DESCRIPTION
**Pull request by BakermanLP**
from AluraDev/TerrainControl commit d9d47c6a3181ce6fd4acabbecd9f41693b6ec4b4

A bit more logging!

### CODE REVIEW

**Comment by rutgerkok** [comment]
Looks nice!

However, I think that the `Biome {} has a ReplaceToBiomeName specified of {}` message is unnecessary, it just reports the value of a setting. Woth a lot of biomes, this will get spammy.

Also, you are not the author of the code submitted here. I don't know if it's required legally, but I want permission of the original author before this code is merged.

**Comment by BakermanLP** [comment]
You are right. I mentioned his name in the commit and pull request.

Rutger Kok <notifications@github.com> schrieb am Mi., 12. Okt. 2016, 19:02:

**Comment by rutgerkok** [comment]
Mentioning a name is not enough, in my opinion. I really want permission from the original author.

**Comment by BakermanLP** [comment]
@AlmuraDev : Would you mind, if we use some of your changes here?

**Comment by mcsnetworks** [comment]
I have no issues if you want to use that code.  Although I could do a much better job than I did.

**Comment by BakermanLP** [comment]
What should be changed?

**Comment by mcsnetworks** [comment]
@BakermanLP I'm adding some more debugging.  We seem to have got multi-worlds working under Forge now I am just debugging the biome registrations.

https://github.com/AlmuraDev/TerrainControl/commits/master

**Comment by BakermanLP** [comment]
I will make a new pull request after checking the new commit.

**Pull request closed without merging**
